#!/usr/bin/env node
/**
 * SL-12: the README's own `npm start` crashed on Express 5, because the SPA
 * catch-all used a bare "*". Nothing caught it, because nothing ever started the
 * production server. This does — in CI, on every push.
 *
 * SL-19: it boots the SOURCE entry via tsx by default, not the committed bundle.
 * The committed bundle was regenerated by hand and drifted from source; when this
 * check was first run it happily reproduced the PathError from a bundle built
 * before the fix. Set BOOT_CHECK_TARGET=bundle to check a freshly built artifact.
 */
import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';

const useBundle = process.env.BOOT_CHECK_TARGET === 'bundle';
const target = useBundle ? 'api/index.cjs' : 'src/api/index.ts';

if (useBundle && !existsSync(target)) {
  console.error(`boot-check: ${target} missing — run "npm run build:node" first.`);
  process.exit(1);
}

const cmd = useBundle ? ['node', [target]] : ['npx', ['tsx', target]];

const proc = spawn(cmd[0], cmd[1], {
  env: { ...process.env, NODE_ENV: 'production', PORT: '3941', OPENAI_API_KEY: '' },
  stdio: ['ignore', 'pipe', 'pipe'],
});

let out = '';
proc.stdout.on('data', (d) => { out += d; });
proc.stderr.on('data', (d) => { out += d; });

const listening = new Promise((resolve) => {
  const check = () => { if (/Server running on/.test(out)) resolve('listening'); };
  proc.stdout.on('data', check);
  proc.stderr.on('data', check);
});

const result = await Promise.race([
  listening,
  new Promise((r) => proc.on('exit', (c) => r(`exit:${c}`))),
  new Promise((r) => setTimeout(() => r('timeout'), 25000)),
]);

proc.kill('SIGTERM');

const fatal = /PathError|Missing parameter name|TypeError|ReferenceError|SyntaxError/.exec(out);
if (fatal) {
  console.error(`boot-check FAILED (${target}): ${fatal[0]} during boot\n`);
  console.error(out.split('\n').slice(0, 14).join('\n'));
  process.exit(1);
}
if (result.startsWith('exit:') && result !== 'exit:null' && result !== 'exit:0') {
  console.error(`boot-check FAILED (${target}): process exited ${result}\n${out}`);
  process.exit(1);
}
if (result === 'timeout') {
  console.error(`boot-check FAILED (${target}): never reported listening within 25s\n${out}`);
  process.exit(1);
}
console.log(`boot-check: ${target} started cleanly in production mode on :3941`);
